// Package api_types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api_types

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Action defines model for Action.
type Action struct {
	ActionType  string                 `json:"action_type"`
	CorrId      string                 `json:"corr_id"`
	CreatedAt   string                 `json:"created_at"`
	Details     map[string]interface{} `json:"details"`
	Error       string                 `json:"error"`
	Id          int64                  `json:"id"`
	PortfolioId int64                  `json:"portfolio_id"`
	SubId       int64                  `json:"sub_id"`
}

// ActionListResponse defines model for ActionListResponse.
type ActionListResponse struct {
	Code    int      `json:"code"`
	Data    []Action `json:"data"`
	Message string   `json:"message"`
}

// Customer defines model for Customer.
type Customer struct {
	Id       int64  `json:"id"`
	Pnl      string `json:"pnl"`
	Username string `json:"username"`
}

// CustomerListResponse defines model for CustomerListResponse.
type CustomerListResponse struct {
	Code    int        `json:"code"`
	Data    []Customer `json:"data"`
	Message string     `json:"message"`
}

// Fren defines model for Fren.
type Fren struct {
	Description string      `json:"description"`
	Id          int64       `json:"id"`
	ImageBase64 string      `json:"image_base64"`
	Name        string      `json:"name"`
	Portfolios  []Portfolio `json:"portfolios"`
}

// FrenListResponse defines model for FrenListResponse.
type FrenListResponse struct {
	Code    int    `json:"code"`
	Data    []Fren `json:"data"`
	Message string `json:"message"`
}

// Holding defines model for Holding.
type Holding struct {
	Coin    string `json:"coin"`
	CoinImg string `json:"coin_img"`
	Percent string `json:"percent"`
}

// IdResponse defines model for IdResponse.
type IdResponse struct {
	Code int `json:"code"`
	Data struct {
		// Id allocated internal id of the customer
		Id int64 `json:"id"`
	} `json:"data"`
	Message string `json:"message"`
}

// InviteTokensResponse defines model for InviteTokensResponse.
type InviteTokensResponse struct {
	Code    int      `json:"code"`
	Data    []string `json:"data"`
	Message string   `json:"message"`
}

// Portfolio defines model for Portfolio.
type Portfolio struct {
	AvgDelay               string    `json:"avg_delay"`
	CycleInvestmentPercent string    `json:"cycle_investment_percent"`
	DcaLevels              int       `json:"dca_levels"`
	Description            string    `json:"description"`
	Holdings               []Holding `json:"holdings"`
	Id                     int64     `json:"id"`
	ImageBase64            string    `json:"image_base64"`
	Leverage               int       `json:"leverage"`
	Name                   string    `json:"name"`
	RiskLevel              string    `json:"risk_level"`
	StrategyType           string    `json:"strategy_type"`
	YearPnl                string    `json:"year_pnl"`
}

// PortfolioListResponse defines model for PortfolioListResponse.
type PortfolioListResponse struct {
	Code    int         `json:"code"`
	Data    []Portfolio `json:"data"`
	Message string      `json:"message"`
}

// Response defines model for Response.
type Response struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// SettingsResponse defines model for SettingsResponse.
type SettingsResponse struct {
	Code int `json:"code"`
	Data struct {
		Settings struct {
			BybitApiKey        string `json:"bybit_api_key"`
			BybitApiSecret     string `json:"bybit_api_secret"`
			BybitTestApiKey    string `json:"bybit_test_api_key"`
			BybitTestApiSecret string `json:"bybit_test_api_secret"`
			Country            string `json:"country"`
			Gender             string `json:"gender"`
			ImageBase64        string `json:"image_base64"`
			LegalName          string `json:"legal_name"`
			PhoneNumber        string `json:"phone_number"`
			Username           string `json:"username"`
		} `json:"settings"`
	} `json:"data"`
	Message string `json:"message"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	Amount      string  `json:"amount"`
	CreatedAt   string  `json:"created_at"`
	Exchange    *string `json:"exchange,omitempty"`
	Id          int64   `json:"id"`
	IsTest      bool    `json:"is_test"`
	Pnl         string  `json:"pnl"`
	PortfolioId int64   `json:"portfolio_id"`
	Status      string  `json:"status"`
	UpdatedAt   string  `json:"updated_at"`
}

// SubscriptionListResponse defines model for SubscriptionListResponse.
type SubscriptionListResponse struct {
	Code    int            `json:"code"`
	Data    []Subscription `json:"data"`
	Message string         `json:"message"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	Code int `json:"code"`
	Data struct {
		// Token token to use in Auth header for all the auth endpoints
		Token string `json:"token"`
	} `json:"data"`
	Message string `json:"message"`
}

// Trade defines model for Trade.
type Trade struct {
	Commission  string `json:"commission"`
	CorrId      string `json:"corr_id"`
	CreatedAt   string `json:"created_at"`
	Exchange    string `json:"exchange"`
	Id          int64  `json:"id"`
	PortfolioId int64  `json:"portfolio_id"`
	Price       string `json:"price"`
	Quantity    string `json:"quantity"`
	Side        string `json:"side"`
	SubId       int64  `json:"sub_id"`
	Symbol      string `json:"symbol"`
}

// TradeListResponse defines model for TradeListResponse.
type TradeListResponse struct {
	Code    int     `json:"code"`
	Data    []Trade `json:"data"`
	Message string  `json:"message"`
}

// BadRequestErrorResponse defines model for BadRequestErrorResponse.
type BadRequestErrorResponse = Response

// ForbiddenErrorResponse defines model for ForbiddenErrorResponse.
type ForbiddenErrorResponse = Response

// InternalServerErrorResponse defines model for InternalServerErrorResponse.
type InternalServerErrorResponse = Response

// NotFoundErrorResponse defines model for NotFoundErrorResponse.
type NotFoundErrorResponse = Response

// DeleteV1AdminFrenJSONBody defines parameters for DeleteV1AdminFren.
type DeleteV1AdminFrenJSONBody struct {
	Id int64 `json:"id"`
}

// PostV1AdminFrenJSONBody defines parameters for PostV1AdminFren.
type PostV1AdminFrenJSONBody struct {
	Description  string  `json:"description"`
	ImageBase64  string  `json:"image_base64"`
	Name         string  `json:"name"`
	PortfolioIds []int64 `json:"portfolio_ids"`
}

// PutV1AdminFrenJSONBody defines parameters for PutV1AdminFren.
type PutV1AdminFrenJSONBody struct {
	Description  *string  `json:"description,omitempty"`
	Id           int64    `json:"id"`
	ImageBase64  *string  `json:"image_base64,omitempty"`
	Name         *string  `json:"name,omitempty"`
	PortfolioIds *[]int64 `json:"portfolio_ids,omitempty"`
}

// PostV1AdminGenerateInviteTokenJSONBody defines parameters for PostV1AdminGenerateInviteToken.
type PostV1AdminGenerateInviteTokenJSONBody struct {
	// Count how much tokens to generate. possible values [1,20]
	Count int `json:"count"`
}

// PostV1AdminLoginJSONBody defines parameters for PostV1AdminLogin.
type PostV1AdminLoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// DeleteV1AdminPortfolioJSONBody defines parameters for DeleteV1AdminPortfolio.
type DeleteV1AdminPortfolioJSONBody struct {
	Id int64 `json:"id"`
}

// PostV1AdminPortfolioJSONBody defines parameters for PostV1AdminPortfolio.
type PostV1AdminPortfolioJSONBody struct {
	AvgDelay               string    `json:"avg_delay"`
	CycleInvestmentPercent string    `json:"cycle_investment_percent"`
	DcaLevels              int       `json:"dca_levels"`
	Description            string    `json:"description"`
	Holdings               []Holding `json:"holdings"`
	ImageBase64            string    `json:"image_base64"`
	Leverage               int       `json:"leverage"`
	Name                   string    `json:"name"`
	RiskLevel              string    `json:"risk_level"`
	StrategyType           string    `json:"strategy_type"`
	YearPnl                string    `json:"year_pnl"`
}

// PutV1AdminPortfolioJSONBody defines parameters for PutV1AdminPortfolio.
type PutV1AdminPortfolioJSONBody struct {
	AvgDelay               *string    `json:"avg_delay,omitempty"`
	CycleInvestmentPercent *string    `json:"cycle_investment_percent,omitempty"`
	DcaLevels              *int       `json:"dca_levels,omitempty"`
	Description            *string    `json:"description,omitempty"`
	Holdings               *[]Holding `json:"holdings,omitempty"`
	Id                     int64      `json:"id"`
	ImageBase64            *string    `json:"image_base64,omitempty"`
	Leverage               *int       `json:"leverage,omitempty"`
	Name                   *string    `json:"name,omitempty"`
	PortfolioIds           *[]int64   `json:"portfolio_ids,omitempty"`
	RiskLevel              *string    `json:"risk_level,omitempty"`
	StrategyType           *string    `json:"strategy_type,omitempty"`
	YearPnl                *string    `json:"year_pnl,omitempty"`
}

// PostV1TvJSONBody defines parameters for PostV1Tv.
type PostV1TvJSONBody struct {
	Action       string `json:"action"`
	Exchange     string `json:"exchange"`
	StrategyName string `json:"strategy_name"`
	Symbol       string `json:"symbol"`
}

// PostV1UserLoginJSONBody defines parameters for PostV1UserLogin.
type PostV1UserLoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostV1UserPortfolioSubscribeJSONBody defines parameters for PostV1UserPortfolioSubscribe.
type PostV1UserPortfolioSubscribeJSONBody struct {
	Amount      string `json:"amount"`
	IsTest      bool   `json:"is_test"`
	PortfolioId int64  `json:"portfolio_id"`
}

// PostV1UserPortfolioUnsubscribeJSONBody defines parameters for PostV1UserPortfolioUnsubscribe.
type PostV1UserPortfolioUnsubscribeJSONBody struct {
	SubscriptionId int64 `json:"subscription_id"`
}

// PostV1UserRegisterJSONBody defines parameters for PostV1UserRegister.
type PostV1UserRegisterJSONBody struct {
	InviteToken string `json:"invite_token"`
	Password    string `json:"password"`
	Username    string `json:"username"`
}

// PutV1UserSettingsJSONBody defines parameters for PutV1UserSettings.
type PutV1UserSettingsJSONBody struct {
	BybitApiKey        *string `json:"bybit_api_key,omitempty"`
	BybitApiSecret     *string `json:"bybit_api_secret,omitempty"`
	BybitTestApiKey    *string `json:"bybit_test_api_key,omitempty"`
	BybitTestApiSecret *string `json:"bybit_test_api_secret,omitempty"`
	Country            *string `json:"country,omitempty"`
	Gender             *string `json:"gender,omitempty"`
	ImageBase64        *string `json:"image_base64,omitempty"`
	LegalName          *string `json:"legal_name,omitempty"`
	PhoneNumber        *string `json:"phone_number,omitempty"`
}

// DeleteV1AdminFrenJSONRequestBody defines body for DeleteV1AdminFren for application/json ContentType.
type DeleteV1AdminFrenJSONRequestBody DeleteV1AdminFrenJSONBody

// PostV1AdminFrenJSONRequestBody defines body for PostV1AdminFren for application/json ContentType.
type PostV1AdminFrenJSONRequestBody PostV1AdminFrenJSONBody

// PutV1AdminFrenJSONRequestBody defines body for PutV1AdminFren for application/json ContentType.
type PutV1AdminFrenJSONRequestBody PutV1AdminFrenJSONBody

// PostV1AdminGenerateInviteTokenJSONRequestBody defines body for PostV1AdminGenerateInviteToken for application/json ContentType.
type PostV1AdminGenerateInviteTokenJSONRequestBody PostV1AdminGenerateInviteTokenJSONBody

// PostV1AdminLoginJSONRequestBody defines body for PostV1AdminLogin for application/json ContentType.
type PostV1AdminLoginJSONRequestBody PostV1AdminLoginJSONBody

// DeleteV1AdminPortfolioJSONRequestBody defines body for DeleteV1AdminPortfolio for application/json ContentType.
type DeleteV1AdminPortfolioJSONRequestBody DeleteV1AdminPortfolioJSONBody

// PostV1AdminPortfolioJSONRequestBody defines body for PostV1AdminPortfolio for application/json ContentType.
type PostV1AdminPortfolioJSONRequestBody PostV1AdminPortfolioJSONBody

// PutV1AdminPortfolioJSONRequestBody defines body for PutV1AdminPortfolio for application/json ContentType.
type PutV1AdminPortfolioJSONRequestBody PutV1AdminPortfolioJSONBody

// PostV1TvJSONRequestBody defines body for PostV1Tv for application/json ContentType.
type PostV1TvJSONRequestBody PostV1TvJSONBody

// PostV1UserLoginJSONRequestBody defines body for PostV1UserLogin for application/json ContentType.
type PostV1UserLoginJSONRequestBody PostV1UserLoginJSONBody

// PostV1UserPortfolioSubscribeJSONRequestBody defines body for PostV1UserPortfolioSubscribe for application/json ContentType.
type PostV1UserPortfolioSubscribeJSONRequestBody PostV1UserPortfolioSubscribeJSONBody

// PostV1UserPortfolioUnsubscribeJSONRequestBody defines body for PostV1UserPortfolioUnsubscribe for application/json ContentType.
type PostV1UserPortfolioUnsubscribeJSONRequestBody PostV1UserPortfolioUnsubscribeJSONBody

// PostV1UserRegisterJSONRequestBody defines body for PostV1UserRegister for application/json ContentType.
type PostV1UserRegisterJSONRequestBody PostV1UserRegisterJSONBody

// PutV1UserSettingsJSONRequestBody defines body for PutV1UserSettings for application/json ContentType.
type PutV1UserSettingsJSONRequestBody PutV1UserSettingsJSONBody
